<?php

namespace App\Enums;

use App\Traits\Enum\EnumTrait;

enum BrandEnum: int
{
    use EnumTrait;

    case ACURA = 1;
    case ALFA_ROMEO = 2;
    case ALPINA = 3;
    case ARO = 4;
    case ASIA = 5;
    case ASTON_MARTIN = 6;
    case AUDI = 7;
    case BAIC = 8;
    case BENTLEY = 9;
    case BMW = 10;
    case BRILLIANCE = 11;
    case BUICK = 12;
    case BYD = 13;
    case CADILLAC = 14;
    case CHANGAN = 15;
    case CHERY = 16;
    case CHEVROLET = 17;
    case CHRYSLER = 18;
    case CITROEN = 19;
    case CUPRA = 20;
    case DACIA = 21;
    case DAEWOO = 22;
    case DAIHATSU = 23;
    case DATSUN = 24;
    case DERWAYS = 25;
    case DODGE = 26;
    case DONGFENG = 27;
    case DONGFENG_HONDA = 28;
    case EAGLE = 29;
    case EVERUS = 30;
    case FAW = 31;
    case FERRARI = 32;
    case FIAT = 33;
    case FISKER = 34;
    case FORD = 35;
    case FOTON = 36;
    case FSO = 37;
    case GAC = 38;
    case GAC_HONDA = 39;
    case GEELY = 40;
    case GENESIS = 41;
    case GMC = 42;
    case GONOW = 43;
    case GREAT_WALL = 44;
    case HAFEI = 45;
    case HAIMA = 46;
    case HAVAL = 47;
    case HONDA = 48;
    case HONGXING = 49;
    case HUMMER = 50;
    case HYUNDAI = 51;
    case INFINITI = 52;
    case IRAN_KHODRO = 53;
    case ISUZU = 54;
    case JAC = 55;
    case JAGUAR = 56;
    case JEEP = 57;
    case JIANGLING = 58;
    case JOYLONG = 59;
    case KANDI = 60;
    case KIA = 61;
    case LADA_VAZ = 62;
    case LAMBORGHINI = 63;
    case LANCIA = 64;
    case LAND_ROVER = 65;
    case LEXUS = 66;
    case LIFAN = 67;
    case LINCOLN = 68;
    case LIXIANG = 69;
    case LOTUS = 70;
    case MAHINDRA = 71;
    case MASERATI = 72;
    case MAYBACH = 73;
    case MAZDA = 74;
    case MCLAREN = 75;
    case MERCEDES_BENZ = 76;
    case MERCURY = 77;
    case MG = 78;
    case MICROCAR = 79;
    case MINI = 80;
    case MITSUBISHI = 81;
    case MORGAN = 82;
    case NISSAN = 83;
    case OLDSMOBILE = 84;
    case OPEL = 85;
    case PEUGEOT = 86;
    case PIAGGIO = 87;
    case PLYMOUTH = 88;
    case POLESTAR = 89;
    case PONTIAC = 90;
    case PORSCHE = 91;
    case PROTON = 92;
    case RAM = 93;
    case RAVON = 94;
    case RENAULT = 95;
    case RENAULT_SAMSUNG = 96;
    case ROEWE = 97;
    case ROLLS_ROYCE = 98;
    case ROVER = 99;
    case SAAB = 100;
    case SAIPA = 101;
    case SANTANA = 102;
    case SATURN = 103;
    case SCION = 104;
    case SEAT = 105;
    case SHANGHAI_MAPLE = 106;
    case SKODA = 107;
    case SMART = 108;
    case SSANGYONG = 109;
    case SUBARU = 110;
    case SUZUKI = 111;
    case TATA = 112;
    case TATRA = 113;
    case TESLA = 114;
    case THINK = 115;
    case TIANMA = 116;
    case TOYOTA = 117;
    case TRABANT = 118;
    case VOLKSWAGEN = 119;
    case VOLVO = 120;
    case VORTEX = 121;
    case VOYAH = 122;
    case WARTBURG = 123;
    case WELTMEISTER = 124;
    case XPENG = 125;
    case ZEEKR = 126;
    case ZOTYE = 127;
    case ZX = 128;
    case BOGDAN = 129;
    case GAZ = 130;
    case ERAZ = 131;
    case ZAZ = 132;
    case IZ = 133;
    case LUAZ = 134;
    case MOSKVIC = 135;
    case RAF = 136;
    case TAGAZ = 137;
    case UAZ = 138;
    case EKSKLIUZIV = 139;
    case DENZA = 140;

    /**
     * @return string
     */
    public function title(): string
    {
        return match ($this) {
            self::ACURA => 'Acura',
            self::ALFA_ROMEO => 'Alfa Romeo',
            self::ALPINA => 'Alpina',
            self::ARO => 'ARO',
            self::ASIA => 'Asia',
            self::ASTON_MARTIN => 'Aston Martin',
            self::AUDI => 'Audi',
            self::BAIC => 'BAIC ',
            self::BENTLEY => 'Bentley',
            self::BMW => 'BMW',
            self::BRILLIANCE => 'Brilliance',
            self::BUICK => 'Buick',
            self::BYD => 'BYD',
            self::CADILLAC => 'Cadillac',
            self::CHANGAN => 'Changan',
            self::CHERY => 'Chery',
            self::CHEVROLET => 'Chevrolet',
            self::CHRYSLER => 'Chrysler',
            self::CITROEN => 'Citroen',
            self::CUPRA => 'Cupra',
            self::DACIA => 'Dacia',
            self::DAEWOO => 'Daewoo',
            self::DAIHATSU => 'Daihatsu',
            self::DATSUN => 'Datsun',
            self::DERWAYS => 'Derways',
            self::DODGE => 'Dodge',
            self::DONGFENG => 'Dongfeng',
            self::DONGFENG_HONDA => 'Dongfeng Honda',
            self::EAGLE => 'Eagle',
            self::EVERUS => 'Everus',
            self::FAW => 'FAW',
            self::FERRARI => 'Ferrari',
            self::FIAT => 'Fiat',
            self::FISKER => 'Fisker',
            self::FORD => 'Ford',
            self::FOTON => 'Foton',
            self::FSO => 'FSO',
            self::GAC => 'GAC',
            self::GAC_HONDA => 'GAC Honda',
            self::GEELY => 'Geely',
            self::GENESIS => 'Genesis',
            self::GMC => 'GMC',
            self::GONOW => 'Gonow',
            self::GREAT_WALL => 'Great Wall',
            self::HAFEI => 'Hafei',
            self::HAIMA => 'Haima',
            self::HAVAL => 'Haval',
            self::HONDA => 'Honda',
            self::HONGXING => 'Hongxing',
            self::HUMMER => 'Hummer',
            self::HYUNDAI => 'Hyundai',
            self::INFINITI => 'Infiniti',
            self::IRAN_KHODRO => 'Iran Khodro',
            self::ISUZU => 'Isuzu',
            self::JAC => 'JAC',
            self::JAGUAR => 'Jaguar',
            self::JEEP => 'Jeep',
            self::JIANGLING => 'Jiangling',
            self::JOYLONG => 'Joylong',
            self::KANDI => 'Kandi',
            self::KIA => 'Kia',
            self::LADA_VAZ => 'Lada (ВАЗ)',
            self::LAMBORGHINI => 'Lamborghini',
            self::LANCIA => 'Lancia',
            self::LAND_ROVER => 'Land Rover',
            self::LEXUS => 'Lexus',
            self::LIFAN => 'Lifan',
            self::LINCOLN => 'Lincoln',
            self::LIXIANG => 'LiXiang',
            self::LOTUS => 'Lotus',
            self::MAHINDRA => 'Mahindra',
            self::MASERATI => 'Maserati',
            self::MAYBACH => 'Maybach',
            self::MAZDA => 'Mazda',
            self::MCLAREN => 'McLaren',
            self::MERCEDES_BENZ => 'Mercedes-Benz',
            self::MERCURY => 'Mercury',
            self::MG => 'MG',
            self::MICROCAR => 'Microcar',
            self::MINI => 'MINI',
            self::MITSUBISHI => 'Mitsubishi',
            self::MORGAN => 'Morgan',
            self::NISSAN => 'Nissan',
            self::OLDSMOBILE => 'Oldsmobile',
            self::OPEL => 'Opel',
            self::PEUGEOT => 'Peugeot',
            self::PIAGGIO => 'Piaggio',
            self::PLYMOUTH => 'Plymouth',
            self::POLESTAR => 'Polestar',
            self::PONTIAC => 'Pontiac',
            self::PORSCHE => 'Porsche',
            self::PROTON => 'Proton',
            self::RAM => 'RAM',
            self::RAVON => 'Ravon',
            self::RENAULT => 'Renault',
            self::RENAULT_SAMSUNG => 'Renault Samsung',
            self::ROEWE => 'Roewe',
            self::ROLLS_ROYCE => 'Rolls-Royce',
            self::ROVER => 'Rover',
            self::SAAB => 'Saab',
            self::SAIPA => 'Saipa',
            self::SANTANA => 'Santana',
            self::SATURN => 'Saturn',
            self::SCION => 'Scion',
            self::SEAT => 'SEAT',
            self::SHANGHAI_MAPLE => 'Shanghai Maple',
            self::SKODA => 'Skoda',
            self::SMART => 'Smart',
            self::SSANGYONG => 'SsangYong',
            self::SUBARU => 'Subaru',
            self::SUZUKI => 'Suzuki',
            self::TATA => 'Tata',
            self::TATRA => 'Tatra',
            self::TESLA => 'Tesla',
            self::THINK => 'Think',
            self::TIANMA => 'Tianma',
            self::TOYOTA => 'Toyota',
            self::TRABANT => 'Trabant',
            self::VOLKSWAGEN => 'Volkswagen',
            self::VOLVO => 'Volvo',
            self::VORTEX => 'Vortex',
            self::VOYAH => 'Voyah',
            self::WARTBURG => 'Wartburg',
            self::WELTMEISTER => 'Weltmeister',
            self::XPENG => 'Xpeng',
            self::ZEEKR => 'Zeekr',
            self::ZOTYE => 'Zotye',
            self::ZX => 'ZX',
            self::BOGDAN => 'Богдан',
            self::GAZ => 'ГАЗ',
            self::ERAZ => 'ЕрАЗ',
            self::ZAZ => 'ЗАЗ',
            self::IZ => 'ИЖ',
            self::LUAZ => 'ЛуАЗ',
            self::MOSKVIC => 'Москвич',
            self::RAF => 'РАФ',
            self::TAGAZ => 'ТагАЗ',
            self::UAZ => 'УАЗ',
            self::EKSKLIUZIV => 'Эксклюзив',
            self::DENZA => 'Denza'
        };
    }
}
